### ISSUE TITLE
sig-scale: features for automating benchmarking

### ISSUE THREAD

**Issue by alaypatel07** [kubevirt/kubevirt#10083]
Sig-scale released a bunch of benchmarks as part of release-1.0. However,
there are improvements needed to the benchmarks as well as automation to 
publish the graphs every week. This issue is extension of https://github.com/kubevirt/project-infra/issues/2705

- [ ] Automation:
   -  [ ] CI post-submit job is needed to plot graphs in ci-performance-benchmarks repository https://github.com/kubevirt/project-infra/issues/2926
   -  [ ] CI should have a way to screenshots benchmarks in ci-performance-benchmarks repository for badges 

- [ ] Benchmarks enhancements:
    - [ ] enhance perf-report-creator to include VM with instancetype and preference metrics  https://github.com/kubevirt/project-infra/issues/2874
    - [ ] consider averages for performance benchmarks
   
- [ ] Documentation:
   - [ ] add a section to user-guide for benchmarks https://github.com/kubevirt/user-guide/issues/693
   - [ ] add a section to user-guid for tooling

**Comment by alaypatel07** [comment]
cc @rthallisey created this is for sig-scale post v1 tasks.
