### ISSUE TITLE
Cold "Resize" while maintaining VM identity.

### ISSUE THREAD

**Issue by xsgordon** [kubevirt/kubevirt#1029]
As a user I would like to be able to change the CPU, RAM, or Disk of an offline virtual machine while maintaining its identity (UUIDs, MAC, etc.). Changes would take effect the next time the virtual machine is instantiated.

- [x] Keep SMBIOS UUID 
- [x] Keep vNIC MAC https://github.com/kubevirt/kubevirt/issues/1069
- [x] Keep disk serial https://github.com/kubevirt/kubevirt/issues/1133

**Comment by rmohr** [comment]
That is exactly what is happening right now. Did you run into some issues?

**Comment by rmohr** [comment]
Ah ok, MAC is not kept. Do you have a more concrete list? Since all the other things you mention are working like you are requesting.

**Comment by rmohr** [comment]
@vladikr FYI regarding to the MAC.

**Comment by vladikr** [comment]
> would keeping the MAC keep the IP address?
It depends on the CNI provider I suppose. Some have DHCP and some don't. Also, what if the VM starts after the lease has been expired...

The MAC and IP are not kept because we discover the network interface in the pod each time we start a vm. Keeping the MAC should be possible, but to guaranteeing the same IP would be tricky.

**Comment by itamarh** [comment]
If dhcp lease expired we still get "normal dhcp behaviour". that is fine.
I understand we can't guarantee it, just stating its probably the main reason to keeping the mac, so we should have it in the back of our heads.

**Comment by stu-gott** [comment]
@vladikr MAC address is commonly used to distinguish DHCP clients for IP address assignment, but there's also client-id/duid for IPv4 and IPv6 respectively.

Glancing at the dnsmasq man page, it seems we could use that instead of hwaddr. Just mentioning that in case it's a more straightforward approach than trying to maintain MAC addresses (which is arguably a good idea for other reasons).

**Comment by xsgordon** [comment]
@rmohr list right now is pretty short:

* MAC
* IP (implied, as it seems that is why they want the MAC)
* SMBIOS UUID

There may be other elements of VM "identity" that we think of based on our experience with oVirt/OpenStack but these are the items that came up in conversation.

**Comment by xsgordon** [comment]
@vladikr we can probably make some disclaimer w.r.t. IP as long as we can keep the MAC. Something along the lines of keeping the IP will depend on these X elements of your network setup.

**Comment by fabiand** [comment]
We nede to differentiate between the features we can control _hard_:
 * MAC
* SMBIOS UUID

because they are part of the VM frontend.

But IP is a guest sided property. Even if we had control over DHCP, then it would still be a question of the client to use it.

I'm not saying that we don't want to still get the best setup to keep the identity, I'm just trying to clarify the differences between the properties.

Finally, reliable DHCP with the properties we assume will only be possible with additional network interfaces which connect to networks which behave as we expect.

**Comment by fabiand** [comment]
Another note - With the discussed network API we will be able to control the mac of (multiple) interfaces, this should close the ramining gap of at least the list above.

**Comment by fabiand** [comment]
MAC part depends on https://github.com/kubevirt/kubevirt/issues/1067

**Comment by fabiand** [comment]
Macking this a tracker as all individual items got bugs now.

**Comment by fabiand** [comment]
All done.
