### ISSUE TITLE
[tracker] API changes

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#1576]
A couple of API changes we want to do:

- [x] volumeName https://github.com/kubevirt/kubevirt/pull/1570 (probably a breaking change/non migratable)
- [x] registryDisk #1730
- [x] launcher ownerReference https://github.com/kubevirt/kubevirt/pull/1641/
- [x] q35 https://github.com/kubevirt/kubevirt/pull/1718
- [x] dedicated namespace https://github.com/kubevirt/kubevirt/issues/1553
- ~[ ] move to quay #1044 ~ (not to be considered an api)
- [x] make name field in interface status required #1595  (?)
- ~[ ] version handler grpc api~ (internal api)

They will be done some time before v1.

**Comment by rmohr** [comment]
> They will be done before v1

@fabiand probably also bevore `v1beta1`?

**Comment by fabiand** [comment]
Well, could be.

To me it would e important that we look through our API and see what we
think should be changed - to have a good bag of changes.
I'm fine in then doing the changes before 1b1 - I think it's even good -
thenw e have more time to stabilize on the settled API.

**Comment by fabiand** [comment]
>     * should we allow qemu nic model on the spec or infer it? #1567

How should we be able to infer the correct NIC model?

**Comment by rmohr** [comment]
> @rmohr How should we be able to infer the correct NIC model?

yep comment does probably not make any sense.

**Comment by fabiand** [comment]
Done
