### ISSUE TITLE
Stabilize functional tests on Jenkins

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#206]
* [x] Fix ~~#27~~, to avoid unreachable virt-api scenarios
 * [x] Work around https://github.com/kubernetes/kubernetes/issues/31123
 * [x] Improve kubernetes health checking before starting the tests
 * [ ] Collect events for later investigation, #222 
 * [ ] Collect logs for later investigation, #222 
 * [x] Stabilize test with definition "Should update the Status.MigrationNodeName after the migration target pod was started"
 * [x] If libvirt connection breaks, re-register event callbacks, to not loose events

**Comment by fabiand** [comment]
Stbale for now.
