### ISSUE TITLE
Provide reference manifests for deployment on "any" Kubernetes cluster (i.e. minikube, OpenShift)

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#265]
> As an admin I want to be able to deploy kubevirt with a simple `kubectl` command

KubeVirt aims to be a Kubernetes add-on. As a first step it hould be possible to deploy KubeVirt to an existing cluster using a single `kubectl` command call.

I.e. like
```bash
kubectl apply kubevirt.io/kubevirt.yaml
```

Issues:
* [x] Support arbitrary namespaces (#249)
* [x] Remove master_ip variable from manifest (used for exposing proxies) (@fabiand) (fixed in #538)
* [x] Remove master_ip variable from api server manifest (#457) (fixed in #524)
* [x] use ~ingress controllers~ separate layout from exposure (#387) (also requires the deployment of an ingress controller) (@fabiand) (fixed in #538)
* [x] Remove docker_repo and _tag from manifests (fixed in #538)
* [x] ~Remove specific qemu connection string from manifests (includes hostname today) (will be fixed by pod networking PR)~ (uses ///system for now, no change needed)
* [x] Remove nodeSelectors from manifests (@fabiand) (fixed in #538)
* [x] Optional: Remove primary_nic primary from libvirt manifests (#261) (@vladikr)
* [x] For Origin: Add RBAC rules (#301)
* [x] For Origin: Provide cluster/node/pod policies (#573)

**Comment by fabiand** [comment]
We might want to have automation which is creating manifests based on the manifests from the main repository.

**Comment by rmohr** [comment]
Issues to track, to accomplishe this:

* Support arbitrary namespaces: #249
* Add permissions to the deployment yamls: #301
* Move kubevirt components into their own namespace: #300

**Comment by mpolednik** [comment]
Also looking into this (ansible + openshift + kubernetes addon stack).

**Comment by rmohr** [comment]
Another issue, interesting for consistent KubeVirt bootstrapping is #314 , though not necessarily related to that task.

**Comment by petrkotas** [comment]
The ongoing effort for deployment can be seen in these repositories:
- https://github.com/petrkotas/openshift-env
- https://github.com/cynepco3hahue/kubevirt-ansible

And on adams blog:
- http://adam.younglogic.com/2017/06/kubevirt-on-origin/
- https://adam.younglogic.com/2017/08/custom-kubevirt-manifests/
- http://adam.younglogic.com/2017/08/deploying-kubevirt-on-origin-master/

**Comment by fabiand** [comment]
Closing this issue, there is more in follow ups.
