### ISSUE TITLE
Kubevirt vm with ovs-dpdk

### ISSUE THREAD

**Issue by surekha1723** [kubevirt/kubevirt#3405]
**What happened:**
I am trying to  create VM that can use the vhost-user capability. I have “OVS+DPDK” along with MULTUS in host
I can use the vhost-user capability for the POD that has container using “UserSpace CNI” but unable to apply the same on kubevirt-vm

**Expected Output:**
Vm should be up running with ovs-dpdk userspace-cni

**Environment:**

KubeVirt version (use virtctl version): v0.26.5
Kubernetes version (use kubectl version): v1.17.5
VM or VMI specifications:
Cloud provider or hardware configuration: OVS-DPDK,
OS (e.g. from /etc/os-release):Ubuntu 18.04

**Error:**
{"component":"virt-launcher","level":"error","msg":"failed to get a link for interface: net1","pos":"podinterface.go:171","reason":"Link not found","timestamp":"2020-05-12T14:35:27.324240Z"}
{"component":"virt-launcher","kind":"","level":"error","msg":"pre start setup for VirtualMachineInstance failed.","name":"testvmovs","namespace":"default","pos":"manager.go:1047","reason":"preparing the pod network failed: Link not found","timestamp":"2020-05-12T14:35:27.324286Z","uid":"8930162d-4b0d-4bba-ac0e-86ff06702e7c"}
{"component":"virt-launcher","kind":"","level":"error","msg":"Failed to sync vmi","name":"testvmovs","namespace":"default","pos":"server.go:161","reason":"preparing the pod network failed: Link not found","timestamp":"2020-05-12T14:35:27.324336Z","uid":"8930162d-4b0d-4bba-ac0e-86ff06702e7c"}

**Yaml for vm using kubevirt**
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: testvmovs
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: testvm
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            bridge: {}
          - bridge: {}
            name: br-4
        resources:
          requests:
            memory: 64M
      networks:
      - name: default
        pod: {}
      - multus:
          networkName: userspace-ovs-net-1
        name: br-4
      volumes:
        - name: containerdisk
           containerDisk:
               image: kubevirt/cirros-registry-disk-demo
        - name: cloudinitdisk
          cloudInitNoCloud:
            userDataBase64: SGkuXG4=

**Comment by dankenigsberg** [comment]
If I understand correctly, PR https://github.com/kubevirt/kubevirt/pull/3208 tries to provide just that.

**Comment by krsacme** [comment]
PR #3208 provides the implementation for vhostuser interface type, since it is a one big PR. lets break it in to smaller PRs (list of tasks and associated PRs with status will be added below) and close PR #3208. 
### Tasks
- [ ] Refeactor getPodInterfaceName API to be used in virtwrap/api package 
- [ ] Create Vhostuser interface API
- [ ] Create virt-launcher Pod resources required for vhostuser interface
- [ ] Create virsh xml elements required for vhostuser interface
- [ ] kubevirtci infra changes to run vhostuser tests
- [ ] Add functests with vhostuser interface
- [ ] VM Migration
- [ ] Remove user and group overrides from kubevirt/libvirt container image project
- [ ] Ensure ``hugetlbfs`` group is available in libvirt container
- [ ] Modify ``hugetlbfs`` group name if vhostuser interface is used in VM
- [ ] Add docs kubevirt/kubevirt repo
- [ ] Add docs in [user-guide](https://github.com/kubevirt/user-guide)

**Comment by ormergi** [comment]
Hey as for kubevirtci part I think you should consider use the `k8s-fedora-1.17.0` provider which has nodes with Fedora OS 
(I also commented at https://github.com/kubevirt/kubevirtci/issues/365)

It could save you lot of time by let you to configure and install missing packages for DPDK at provision stage that already automated like any other kubevirtci provider, instead of figuring out how to workaround this or use another OS.

Please feel free to contact me :wink:
