### ISSUE TITLE
OVS-DPDK support for Kubevirt VM

### ISSUE THREAD

**Issue by atiwaripw** [kubevirt/kubevirt#8873]
Hey team,

We see there was some work done by @krsacme(linked below) and team to get above feature in DPDK. It never made to the upstream though. We have requirement for this for few use cases like Palo alto firewalls. This will be a value addition for Edge and NFV (telcos) deployment scenarios.

Just wanted to check what efforts/steps are needed to get it into upstream.

Previous Pull request and context,

https://github.com/kubevirt/kubevirt/pull/3208
https://github.com/kubevirt/kubevirt/issues/3405#issuecomment-659373177

        PR #3208 provides the implementation for vhostuser interface type, since it is a one big PR. lets break it in to smaller PRs (list of tasks and associated PRs with status will be added below) and close PR #3208. 

### Tasks
- [ ] Refeactor getPodInterfaceName API to be used in virtwrap/api package - PR #3843 
- [ ] Create Vhostuser interface API - PR #3888
- [ ] Create virt-launcher Pod resources required for vhostuser interface - PR #3888
- [ ] Create virsh xml elements required for vhostuser interface
- [ ] kubevirtci infra changes to run vhostuser tests -  kubevirt/kubevirtci#365
- [ ] Add functests with vhostuser interface
- [ ] VM Migration
- [ ] Remove user and group overrides from kubevirt/libvirt container image project - https://github.com/kubevirt/libvirt/pull/56
- [ ] Ensure ``hugetlbfs`` group is available in libvirt container
- [ ] Modify ``hugetlbfs`` group name if vhostuser interface is used in VM
- [ ] Add docs kubevirt/kubevirt repo
- [ ] Add docs in [user-guide](https://github.com/kubevirt/user-guide)

_Originally posted by @krsacme in https://github.com/kubevirt/kubevirt/issues/3405#issuecomment-659373177_

**Comment by EdDev** [comment]
I remember two points which have been raised at the time and I think are still relevant:
- SR-IOV hardware advancement (especially in price, availability and VF density per PF) has made OVS-DPDK less attractive on many scenarios. It was not clear if it is worth the effort to invest in this and support it.
- Due to the code base structure which implements the different bindings in kubevirt, it is hard to isolate such additions from the rest of the code. This in turn raises a maintenance burden on the project maintainers.
There have been ideas how to treat this, but no work has started in the direction yet.

If the second point is resolved, the first part may be implicitly irrelevant. Just because it will be a "plugin" which does not have to be in the project core, or it can be isolated and maintained by the authors owning it.

**Comment by EdDev** [comment]
Thank you @poonam-agarwal28 for the inputs.

I have two questions in regards to your description of the scenarios:
- If we had an hot(un)plug option for VFs, would that have solved some of your scenarios?
- it was mentioned several times that the expected traffic throughput is relatively low. If this is the case, what is the reason for not having "regular" (virtual) interfaces instead?

We are seeing that the community has special needs which go beyond the core functionality we currently maintain.
It does make sense to me to allow a pluggable solution here, where the KubeVirt core will support a generic API through which others can plug their own special solution.
Would you be able (and willing) to curate the needed changes and maintain them while KubeVirt will provide an integration point to plug it in?

For example, @AlonaKaplan has suggested some time ago to offload most of the network binding logic to a meta CNI, which is maintained outside kubevirt/kubevirt, and the only part left for the core is to take a resulting device (e.g. a tap device) and bind it to the domain.

**Comment by poonam-agarwal28** [comment]
@EdDev 
Would you be able (and willing) to curate the needed changes and maintain them while KubeVirt will provide an integration point to plug it in?
This is something that we can try. However can you please confirm what do we need in the plugin and what will be provided by the Kubevirt core ?

**Comment by EdDev** [comment]
>> Would you be able (and willing) to curate the needed changes and maintain them while KubeVirt will provide an integration point to plug it in?

> This is something that we can try. However can you please confirm what do we need in the plugin and what will be provided by the Kubevirt core ?

I want to clarify that this ability does not exist yet, we have been thinking about it due to several requests from the community to add special bindings.

One of the ideas raised, is to have a generic binding that takes a tap device and plugges it in the domain.
The tap itself and all the wiring of it to the node to be done by a CNI (or a chain of them).
If you have other ideas of how to do this, you are welcome to suggest it as well.
This CNI codebase will be maintained in a separate repo by its authors and it will have to be deployed on the nodes independently.

Although we have not started planning/working on this yet, it will help promote it if members of the community see value in it and confirm that they are willing to invest in such a solution.
